name: Publish to prod Backend

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    environment:
      name: Production
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node with NVM
      run: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm use node

    - name: Install dependencies
      run: |
        sudo -S apt-get update
        npm install -g @angular/cli
        npm install http-server -g

    - name: Install node modules
      run: |
          npm install --legacy-peer-deps

    - name: Serve
      run: |
        ng serve --port 9530
