name: Publish to prod Backend

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    environment:
      name: Production
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo -S apt-get update

    - name: Install node modules
      run: |
          npm install --legacy-peer-deps

    - name: Serve
      run: |
        ng serve --port 9530
