name: Publish to prod Backend

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    environment:
      name: Production
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node with NVM
      run: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm use node

    - name: Install dependencies
      run: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm use node
        sudo -S apt-get update
        npm install -g @angular/cli

    - name: Install node modules
      run: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm use node
        npm install --legacy-peer-deps
        npm install @angular/localize --legacy-peer-deps

    - name: Build Angular Project
      run: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm use node
        ng build --configuration production

    - name: Test
      run: |
        sudo nginx -t

    - name: Serve
      run: |
        sudo systemctl restart nginx.service
